name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        # Add test commands when you have tests
        echo "Running tests..."
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/chavrutai-app:latest
          ghcr.io/${{ github.repository_owner }}/chavrutai-app:${{ github.sha }}
    
    # You would add deployment steps here specific to your hosting platform
    # For example, if using Google Cloud Run:
    # - name: Deploy to Cloud Run
    #   uses: google-github-actions/deploy-cloudrun@v0
    #   with:
    #     service: chavrutai-app
    #     image: ghcr.io/${{ github.repository_owner }}/chavrutai-app:${{ github.sha }}
    #     region: us-central1
    #     credentials: ${{ secrets.GCP_SA_KEY }}